//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achat
    {
        public int AchatID { get; set; }
        public Nullable<decimal> Cout { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public Nullable<int> VersionID { get; set; }
        public string CartID { get; set; }
        public Nullable<int> ReleveTransactionID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Version Version { get; set; }
        public virtual ReleveTransaction ReleveTransaction { get; set; }
    }
}
