//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biographie
    {
        public int BiographieID { get; set; }
        public string Biographie1 { get; set; }
        public Nullable<System.DateTime> DateDernierChangement { get; set; }
        public int ArtisteID { get; set; }
    
        public virtual Artiste Artiste { get; set; }
    }
}
