//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chanson
    {
        public Chanson()
        {
            this.Version = new HashSet<Version>();
            this.Compositeur = new HashSet<Compositeur>();
        }
    
        public int ChansonID { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Titre { get; set; }
        public Nullable<int> GenreID { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Version> Version { get; set; }
        public virtual ICollection<Compositeur> Compositeur { get; set; }
    }
}
