//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleveTransaction
    {
        public ReleveTransaction()
        {
            this.Achat = new HashSet<Achat>();
        }
    
        public int ReleveTransactionID { get; set; }
        public string Acheteur { get; set; }
        public string CoutTotal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<Achat> Achat { get; set; }
    }
}
