//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V2_bdEntities : DbContext
    {
        public V2_bdEntities()
            : base("name=V2_bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achat> Achat { get; set; }
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<Artiste> Artiste { get; set; }
        public virtual DbSet<Biographie> Biographie { get; set; }
        public virtual DbSet<Chanson> Chanson { get; set; }
        public virtual DbSet<Compositeur> Compositeur { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Instrument> Instrument { get; set; }
        public virtual DbSet<Jouer> Jouer { get; set; }
        public virtual DbSet<ReleveTransaction> ReleveTransaction { get; set; }
        public virtual DbSet<Version> Version { get; set; }
    }
}
